//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayakkabi_Projesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayakkabi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ayakkabi()
        {
            this.AyakkabiNumaras = new HashSet<AyakkabiNumara>();
            this.Indirims = new HashSet<Indirim>();
            this.Onerilenlers = new HashSet<Onerilenler>();
            this.Siparis = new HashSet<Sipari>();
        }
    
        public int AyakkabiID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int KategoriID { get; set; }
        public int Fiyat { get; set; }
        public string Resimyolu { get; set; }
        public string Renk { get; set; }
        public string Malzeme { get; set; }
        public string Baglamasekli { get; set; }
        public Nullable<int> Taksitlifiyat { get; set; }
        public string Sezon { get; set; }
        public Nullable<int> AltKategoriID { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AyakkabiNumara> AyakkabiNumaras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indirim> Indirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Onerilenler> Onerilenlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sipari> Siparis { get; set; }
    }
}
