//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayakkabi_Projesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AyakkabiNumara
    {
        public int AyakkabiNumaraID { get; set; }
        public int AyakkabiID { get; set; }
        public int NumaraID { get; set; }
        public int Stok { get; set; }
    
        public virtual Ayakkabi Ayakkabi { get; set; }
        public virtual Numara Numara { get; set; }
    }
}
