//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayakkabi_Projesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indirim
    {
        public int IndirimID { get; set; }
        public int AyakkabiID { get; set; }
        public Nullable<int> IndirimOrani { get; set; }
    
        public virtual Ayakkabi Ayakkabi { get; set; }
    }
}
