//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayakkabi_Projesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numara
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Numara()
        {
            this.AyakkabiNumaras = new HashSet<AyakkabiNumara>();
        }
    
        public int NumaraID { get; set; }
        public int Numara1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AyakkabiNumara> AyakkabiNumaras { get; set; }
    }
}
